In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score

In [2]:
df=pd.read_csv("D:\Jupyter_notebook_ws\BE Project Machine Learning\Diabetes\cleaned_dataset_of_diabetes.csv")
df=df.iloc[:,1:]
df.sample(10)

AGE      Urea     HbA1c      Chol        TG      VLDL       BMI  \
425  0.532503  0.378976  0.426003  0.908714  0.554633  0.983402  0.831006   
86   0.001285  0.953665  0.024896  0.338866  0.841632  0.336791  0.073306   
454  0.311203  0.455048  0.616874  0.821577  0.841632  0.816736  0.365837   
36   0.075380  0.016598  0.111342  0.047718  0.153527  0.096819  0.035961   
913  0.031120  0.562241  0.247580  0.732365  0.554633  0.441217  0.757953   
585  0.961272  0.476487  0.964730  0.377593  0.487552  0.441217  0.432918   
414  0.532503  0.121715  0.057400  0.446750  0.029046  0.687414  0.922545   
248  0.807746  0.016598  0.289073  0.957123  0.603734  0.605118  0.304979   
14   0.216459  0.221300  0.024896  0.235823  0.270401  0.251729  0.157676   
555  0.807746  0.641770  0.226141  0.636238  0.270401  0.542185  0.978562   

     CLASS  
425      2  
86       0  
454      2  
36       0  
913      2  
585      2  
414      2  
248      2  
14       0  
555      2

In [3]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [4]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=86)
smote=SMOTE()
X_resampled,y_resampled=smote.fit_resample(X_train,y_train)
y_resampled.sample(10)

942     0
383     2
1990    1
1623    1
1564    1
413     2
956     0
1471    1
1948    1
1548    1
Name: CLASS, dtype: int64

In [5]:
# clf=SVC() ##94.5%
# clf=LogisticRegression() ##89%
clf=RandomForestClassifier(n_estimators=500) ##99% class_weight={0: 0.615, 1: 0.331, 2: 0.054}
# clf=GaussianNB() ##94.5%
# clf=XGBClassifier(n_estimators=500) ##99%
# clf.fit(X_train,y_train)
clf.fit(X_resampled,y_resampled)
y_pred=clf.predict(X_test)

In [6]:
metrics = {
    'Accuracy': accuracy_score,
    'Precision': lambda y_true, y_pred: precision_score(y_true, y_pred, average='weighted'),
    'Recall': lambda y_true, y_pred: recall_score(y_true, y_pred, average='weighted'),
    'F1': lambda y_true, y_pred: f1_score(y_true, y_pred, average='weighted'),
    'Confusion Matrix': confusion_matrix,
    'Classification Report': classification_report
}

for name,metric in metrics.items():
    if name in ['Confusion Matrix','Classification Report']:
        print(f"The {name} is: \n {metric(y_test,y_pred)}")
    else:
        print(f"The {name} is: {metric(y_test,y_pred)}")

The Accuracy is: 0.985
The Precision is: 0.9870454545454546
The Recall is: 0.985
The F1 is: 0.985482408806389
The Confusion Matrix is: 
 [[ 19   0   0]
 [  0  10   0]
 [  3   0 168]]
The Classification Report is: 
               precision    recall  f1-score   support

           0       0.86      1.00      0.93        19
           1       1.00      1.00      1.00        10
           2       1.00      0.98      0.99       171

    accuracy                           0.98       200
   macro avg       0.95      0.99      0.97       200
weighted avg       0.99      0.98      0.99       200



In [7]:
scores = cross_val_score(clf, X, y, cv=5)
print("Cross-Validation Scores:", scores)
print("Mean Accuracy:", scores.mean())

Cross-Validation Scores: [0.825 0.99  1.    0.975 0.96 ]
Mean Accuracy: 0.95
